# Definição da versão da API do Kubernetes para Deployment
apiVersion: apps/v1
kind: Deployment
# Metadados do Deployment
metadata:
  # Nome do deployment no namespace
  name: react-deploy
  # Labels para identificar e organizar o recurso
  labels:
    app: reactapp
# Especificações do Deployment
spec:
  # Número de pods que devem estar rodando
  replicas: 1
  # Seletor que define quais pods este deployment gerencia
  selector:
    matchLabels:
      app: reactapp
  # Template para criação dos pods
  template:
    # Metadados aplicados aos pods criados
    metadata:
      labels:
        app: reactapp
    # Especificações dos pods
    spec:
      # Lista de containers que rodarão no pod
      containers:
        - name: reactapp # nome do container
          # Imagem customizada criada no Docker Hub
          image: pedrolshernandes/frontend-p2:latest #meuusergithub/repositorio:tag
          # Portas expostas pelo container
          ports:
            - containerPort: 80
---
# Service para expor a aplicação Node.js para fora do cluster
apiVersion: v1
kind: Service
# Metadados do Service
metadata:
  # Nome do service
  name: reactapp
# Especificações do Service
spec:
  # Configuração das portas
  ports:
    - protocol: TCP                #protocolo
      port: 80                     #porta dentro do container
      targetPort: 80               #porta do container
      nodePort: 30087              #porta externa do cluster
  type: NodePort  # Tipo de serviço para expor a aplicação
  # Seletor para conectar com os pods corretos
  selector:
    app: reactapp #conecta com os pods