// src/utils/habilidades.js

export const opcoesHabilidades = [
    { value: "JavaScript", label: "JavaScript" },
    { value: "TypeScript", label: "TypeScript" },
    { value: "Python", label: "Python" },
    { value: "Java", label: "Java" },
    { value: "C#", label: "C#" },
    { value: "C++", label: "C++" },
    { value: "Go", label: "Go" },
    { value: "Ruby", label: "Ruby" },
    { value: "PHP", label: "PHP" },
    { value: "Swift", label: "Swift" },
    { value: "Kotlin", label: "Kotlin" },
    { value: "Rust", label: "Rust" },
    { value: "HTML", label: "HTML" },
    { value: "CSS", label: "CSS" },
    { value: "Sass", label: "Sass" },
    { value: "Tailwind CSS", label: "Tailwind CSS" },
    { value: "Bootstrap", label: "Bootstrap" },
    { value: "React", label: "React" },
    { value: "Next.js", label: "Next.js" },
    { value: "Vue.js", label: "Vue.js" },
    { value: "Nuxt.js", label: "Nuxt.js" },
    { value: "Angular", label: "Angular" },
    { value: "jQuery", label: "jQuery" },
    { value: "Node.js", label: "Node.js" },
    { value: "Express", label: "Express" },
    { value: "NestJS", label: "NestJS" },
    { value: "Laravel", label: "Laravel" },
    { value: "Symfony", label: "Symfony" },
    { value: "Django", label: "Django" },
    { value: "Flask", label: "Flask" },
    { value: "Spring Boot", label: "Spring Boot" },
    { value: ".NET Core", label: ".NET Core" },
    { value: "RESTful API", label: "RESTful API" },
    { value: "GraphQL", label: "GraphQL" },
    { value: "MySQL", label: "MySQL" },
    { value: "PostgreSQL", label: "PostgreSQL" },
    { value: "MongoDB", label: "MongoDB" },
    { value: "SQLite", label: "SQLite" },
    { value: "Firebase", label: "Firebase" },
    { value: "Redis", label: "Redis" },
    { value: "MariaDB", label: "MariaDB" },
    { value: "Docker", label: "Docker" },
    { value: "Kubernetes", label: "Kubernetes" },
    { value: "AWS", label: "AWS" },
    { value: "Azure", label: "Azure" },
    { value: "Google Cloud", label: "Google Cloud" },
    { value: "CI/CD", label: "CI/CD" },
    { value: "GitHub Actions", label: "GitHub Actions" },
    { value: "Terraform", label: "Terraform" },
    { value: "Jest", label: "Jest" },
    { value: "Mocha", label: "Mocha" },
    { value: "Cypress", label: "Cypress" },
    { value: "Selenium", label: "Selenium" },
    { value: "Playwright", label: "Playwright" },
    { value: "Testing Library", label: "Testing Library" },
    { value: "Git", label: "Git" },
    { value: "GitHub", label: "GitHub" },
    { value: "Figma", label: "Figma" },
    { value: "UX/UI Design", label: "UX/UI Design" },
    { value: "Scrum", label: "Scrum" },
    { value: "Kanban", label: "Kanban" },
    { value: "Trello", label: "Trello" },
    { value: "Notion", label: "Notion" },
    { value: "Linux", label: "Linux" },
    { value: "Shell Script", label: "Shell Script" },
    { value: "React Native", label: "React Native" },
    { value: "Flutter", label: "Flutter" },
    { value: "SwiftUI", label: "SwiftUI" },
    { value: "Kotlin Android", label: "Kotlin Android" },
];
// src/utils/outrasSkills.js

export const outrasSkills = [
    { value: "Comunicação", label: "Comunicação" },
    { value: "Trabalho em equipe", label: "Trabalho em equipe" },
    { value: "Resolução de problemas", label: "Resolução de problemas" },
    { value: "Pensamento crítico", label: "Pensamento crítico" },
    { value: "Liderança", label: "Liderança" },
    { value: "Gestão de tempo", label: "Gestão de tempo" },
    { value: "Autogestão", label: "Autogestão" },
    { value: "Adaptabilidade", label: "Adaptabilidade" },
    { value: "Proatividade", label: "Proatividade" },
    { value: "Empatia", label: "Empatia" },
    { value: "Inteligência emocional", label: "Inteligência emocional" },
    { value: "Inglês", label: "Inglês" },
    { value: "Espanhol", label: "Espanhol" },
    { value: "Francês", label: "Francês" },
    { value: "Alemão", label: "Alemão" },
    { value: "Metodologias Ágeis", label: "Metodologias Ágeis" },
    { value: "Design Thinking", label: "Design Thinking" },
    { value: "Product Discovery", label: "Product Discovery" },
    { value: "Gestão de Projetos", label: "Gestão de Projetos" },
    { value: "Gerenciamento de Stakeholders", label: "Gerenciamento de Stakeholders" },
    { value: "Análise de Dados", label: "Análise de Dados" },
    { value: "Power BI", label: "Power BI" },
    { value: "Excel Avançado", label: "Excel Avançado" },
    { value: "Scrum Master", label: "Scrum Master" },
    { value: "Product Owner", label: "Product Owner" },
    { value: "OKRs", label: "OKRs" },
    { value: "KPI", label: "KPI" },
    { value: "Mapeamento de Processos", label: "Mapeamento de Processos" },
    { value: "BPMN", label: "BPMN" },
    { value: "Lean", label: "Lean" },
    { value: "Six Sigma", label: "Six Sigma" },
    { value: "ISO 9001", label: "ISO 9001" },
    { value: "ITIL", label: "ITIL" },
    { value: "Cybersecurity Basics", label: "Cybersecurity Basics" },
    { value: "LGPD", label: "LGPD" },
    { value: "GDPR", label: "GDPR" },
    { value: "Notion Avançado", label: "Notion Avançado" },
    { value: "Miro", label: "Miro" },
    { value: "Confluence", label: "Confluence" },
    { value: "Jira", label: "Jira" },
    { value: "Slack", label: "Slack" },
    { value: "Comunicação Assíncrona", label: "Comunicação Assíncrona" },
    { value: "Trabalho Remoto", label: "Trabalho Remoto" },
    { value: "Apresentações", label: "Apresentações" },
    { value: "Storytelling", label: "Storytelling" },
    { value: "Mentoria", label: "Mentoria" },
    { value: "Facilitação de Reuniões", label: "Facilitação de Reuniões" },
];
